import type { NextPage } from 'next'
import Head from 'next/head'
import { css } from 'linaria';
import { styled } from 'linaria/react';
import { useState } from 'react';

const color = {
  black: '#000'
} as const;

// cssを定義して使える
const MainStyle = css`
  display: flex;
  flex-direction: column;
  align-items: center;
`;

// 変数の参照もできる
const TitleStyle = css`
  color: ${color.black};
  font-weight: 700;
  font-size: 20px;
`;

// styled-componentsの様な書き方もできる
const Paragraph = styled.p`
  color: #333;
  font-size: 16px;
`;

// propsも受け取れる
const Button = styled.button<{isDisabled: boolean}>`
  background-color: ${props => props.isDisabled ? '#999' : '#fff'};
`;

const Home: NextPage = () => {
  const [isGray, setGray] = useState(false);
  return (
    <>
      <Head>
        <title>Next.js + Linaria sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={MainStyle}>
        <h1 className={TitleStyle}>Next.js + Linaria sample</h1>
        <Paragraph>サンプル</Paragraph>
        <Button isDisabled={isGray} onClick={() => setGray((before) => !before)} >ボタン</Button>
      </main>
    </>
  )
}

export default Home
