[package]
name = "server"
version = "0.1.0"
authors = ["tminasen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.4.0"
actix-rt = "1.1.1"
actix-web = "3.1.0"
serde = "1.0.116"
serde_json = "1.0.59"
