[package]
name = "rust-sample"
version = "0.1.0"
authors = ["@tminasen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
